Feat/challenge 03 loops conditionals
MartiCobos99/JavaScript-foundations-challenge-1 pull request #3
Opened 2023-10-31 18:20 UTC by MartiCobos99

2023-11-05 16:22 UTC, tictools requested changes

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_00.js
> +if (animal === "cat") {
⚠️ FIX: Change animal to different values to make sure it works in all cases

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +if (number % 2 === 0) {
⚠️ FIX: Change the variable to test it works for different cases. Print result.

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_02.js
> +/* To fix this and get the desired output, you should use if-else if-else structure instead of multiple independent if statements.*/
⚠️ FIX: needs work... 🤔

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let number = 10; number <= 40; number += 2) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the even ones

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_00.js
> +for (let number = 11; number <= 39; number += 2) {
These loops should iterate over all numbers in between 10 and 40, printing only the odd/even ones, depending on its own logic.

⚠️ FIX: iterate over all numbers and print only the odd ones

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/loops/exercise_02.js
> +for (let i = 1; i <= 100; i++) {
This is the output of your script
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_00.js
> +while (!loggedIn) {
This is the output of your script...
```
Incorrect login credentials
Successfully logged in!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-05 16:22 UTC, tictools commented on challenge_03_loops-conditionals/loops-conditionals/while/exercise_02.js
> +while (i <= 100) {
This is the output of your script...
```
Checkpoint! 10
Checkpoint! 20
Checkpoint! 30
Checkpoint! 40
Checkpoint! 50
Half way there!
Checkpoint! 60
Checkpoint! 70
Checkpoint! 80
Checkpoint! 90
Checkpoint! 100
You made it!
All, done!
```

...have you tested it before pushing? 🤔

⚠️ FIX: needs work.

2023-11-07 19:18 UTC, AGUACATE2304 requested changes
Needs Works 🚀

2023-11-07 19:18 UTC, AGUACATE2304 commented on challenge_03_loops-conditionals/loops-conditionals/conditionals/exercise_01.js
> +.
FIX: Fatal error. Did you tested the code before upload??

Keep Working 😡

2023-11-12 12:15 UTC, tictools requested changes

2023-11-12 12:15 UTC, tictools commented on challenge_03_loops-conditionals/README.md
FIX: move this file. README should only live at project root level.

2023-11-13 17:35 UTC, AGUACATE2304 approved these changes

2023-11-13 17:39 UTC, tictools approved these changes

2023-11-13 17:39 UTC, merged